language: ruby
rvm:
  - 2.3.3

script:
  - bundle install
  - bundle exec jekyll build

after_script:
  - cd _site
  - git init
  - git checkout master
  - git add .
  - git commit -m "Auto Sync"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

branches:
  only:
    - master
