
language: node_js

# nodejs版本

node_js: 

    - '6'

 

# Travis-CI Caching

cache:

  directories:

    - node_modules


# S: Build Lifecycle

install:

  - npm install

after_script:

  - cd ./dist

  - git init

  - git config user.name "${U_NAME}"

  - git config user.email "${U_EMAIL}"

  - git add .

  - git commit -m "Auto Update Terminus Github Pages"

  - git push --force --depth=1 --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

# E: Build LifeCycle

 

#指定分支，只有指定的分支提交时才会运行脚本

branches:

  only:

    - master
